// Set up web3 instance
const Web3 = require('web3')
const web3 = new Web3('http://localhost:8545') // Local node url (using JSON RPCE)

// Gets contract interface
const { abi } = require('../build/contracts/HelloCoin.json') // This file is generated by truffle during deployment

// 1. Replace this address with your contract address
const helloCoin = new web3.eth.Contract(abi, '0x62d3a560f5c6b4fdeef74db3febd5a9f2ba8a011') // Creates contract instance

console.log('Contract Address => ', helloCoin.options.address)
console.log('Contract Interface => ', helloCoin.methods, '\n')

// 2. Replace this private key from your account private key ('0x' is fixed)
const privateKey = '0x' + '45a6507384d64d148d3e949473da236d750eaf8e23942fc272710319dff7eb6f'
const account = web3.eth.accounts.privateKeyToAccount(privateKey) // Creates an account instance using a private key
const wallet = web3.eth.accounts.wallet.create(0) // Creates a wallet instance
wallet.add(account) // Associates the account with the wallet

console.log('Account Address => ', account.address)

// Retrieves account ETH balance
web3.eth.getBalance(account.address)
  .then(balance => console.log('Account Balance => ', balance, '\n'))

// Check the estimated gas for mint method of HelloCoin contract. This not executes the method, just calculates gas
helloCoin.methods.mint(account.address, 1000)
  .estimateGas({ from: account.address })
  .then(gas => console.log('Estimate Gas', gas))
  .catch(console.log)

// Exec the mint method of HelloCoin contract.
helloCoin.methods.mint(account.address, 1000)
  .send({ from: account.address, gas: 43814 })
  .then(receipt => {
    console.log('TX Receipt', receipt) // Each write operation in the blockchain returns a transaction receipt

    // Calls the getBalance method of HelloCoin contract.
    return helloCoin.methods.getBalance(account.address).call({ from: account.address }) // This will return the balance of HelloCoin tokens, not the ETH balance that we called before
  })
  .then(balance => console.log('Hello Coin Balance', balance))
  .catch(console.log)

